#!/usr/bin/env python3
"""Generates site/index.html (the GitHub Pages website) from scripts/content.py.

Standard library only, so the Pages workflow can run it without installing
anything. Styles and behaviour live in site/style.css and site/main.js.

    python3 scripts/build_site.py
"""
import json
import os
from html import escape
from urllib.parse import quote_plus

import content as C

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, "site")

KIND_LABEL = dict(journal="Journal", conference="Conference", article="Article")
KIND_COLOR = dict(journal="yellow", conference="blue", article="pink")


def e(s):
    return escape(str(s), quote=True)


def pub_url(p):
    return p["url"] or "https://scholar.google.com/scholar?q=" + quote_plus(f'"{p["title"]}"')


def authors_html(authors):
    out = []
    for name in (a.strip() for a in authors.split(",")):
        if name in C.ME:
            out.append(f'<strong class="me">{e(name)}</strong>')
        elif name == C.ADVISOR["author_key"]:
            out.append(f'<span class="adv" title="{e(C.ADVISOR["name"])}, advisor">{e(name)}</span>')
        else:
            out.append(e(name))
    return ", ".join(out)


def nice(label):
    """'GOOGLE SCHOLAR' -> 'Google Scholar', keeping known brand casing."""
    fixed = {"ORCID": "ORCID", "GITHUB": "GitHub"}
    return fixed.get(label, label.title())


def split_title(title):
    """'Name: subtitle' -> ('Name', 'subtitle'), so the system name can be set bold."""
    head, sep, tail = title.partition(": ")
    return (head, tail) if sep and len(head) <= 28 else ("", title)


def publication(i, p):
    head, tail = split_title(p["title"])
    kind = p["kind"]
    title = (f'<span class="pub-name">{e(head)}</span>{e(tail)}' if head else e(tail))
    venue = f'<p class="pub-venue">{e(p["venue"])}</p>' if p["venue"] else ""
    doi = p["url"] and "doi.org/" in p["url"]
    return f"""
      <li class="pub reveal" data-kind="{kind}" style="--c: var(--{KIND_COLOR[kind]})">
        <div class="pub-meta">
          <span class="pub-no">{i:02d}</span>
          <span class="pub-year">{p["year"]}</span>
          <span class="tag">{KIND_LABEL[kind]}</span>
          <a class="pub-link" href="{e(pub_url(p))}" target="_blank" rel="noopener">{"DOI" if doi else "Scholar"} <span aria-hidden="true">↗</span></a>
        </div>
        <h3 class="pub-title"><a href="{e(pub_url(p))}" target="_blank" rel="noopener">{title}</a></h3>
        <p class="pub-authors">{authors_html(p["authors"])}</p>
        {venue}
      </li>"""


def ext(label, url, cls="btn btn-sm"):
    return f'<a class="{cls}" href="{e(url)}" target="_blank" rel="noopener">{e(label)} <span aria-hidden="true">↗</span></a>'


def build():
    pubs = C.PUBLICATIONS
    counts = {k: sum(p["kind"] == k for p in pubs) for k in KIND_LABEL}
    joint = sum(C.ADVISOR["author_key"] in p["authors"] for p in pubs)
    first_year = min(p["year"] for p in pubs)
    adv, lab = C.ADVISOR, C.LAB

    filters = [f'<button class="chip is-on" data-filter="all">All <b>{len(pubs)}</b></button>']
    filters += [
        f'<button class="chip" data-filter="{k}" style="--c: var(--{KIND_COLOR[k]})">'
        f'{KIND_LABEL[k]}s <b>{n}</b></button>'
        for k, n in counts.items() if n
    ]

    links = "\n".join(
        f'<a class="btn btn-{c}" href="{e(u)}" target="_blank" rel="noopener">{e(nice(label))} <span aria-hidden="true">↗</span></a>'
        for label, u, c in C.LINKS
    )
    if C.EMAIL:
        links = f'<a class="btn btn-ink" href="mailto:{e(C.EMAIL)}">Email me</a>\n' + links

    research = "\n".join(
        f"""<li class="area" style="--c: var(--{c})"><h3>{e(t)}</h3><p>{e(b)}</p></li>"""
        for t, b, c in C.RESEARCH
    )

    stack = "\n".join(
        f"""<div class="stack-row" style="--c: var(--{c})">
          <h3>{e(label.title().replace("Zk", "ZK"))}</h3>
          <ul>{"".join(f"<li>{e(x)}</li>" for x in items)}</ul>
        </div>"""
        for label, c, items in C.STACK
    )

    quotes = "\n".join(
        f"""<figure class="quote{' is-on' if i == 0 else ''}">
            <blockquote>{e(q)}</blockquote>
            <figcaption>{e(a)}</figcaption>
          </figure>"""
        for i, (q, a) in enumerate(C.QUOTES)
    )

    # One short line per contract field, so the code box never needs to scroll.
    contract = "".join(
        f'  <span class="ty">{e(t)}</span> {e(k)} = <span class="st">{e(v)}</span>;\n'
        for t, k, v in C.ABOUT
    )

    html = f"""<!doctype html>
<!-- Generated by scripts/build_site.py from scripts/content.py - edit those, not this file. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{e(C.FULL_NAME)} · {e(C.ROLE)}</title>
  <meta name="description" content="{e(C.FULL_NAME)}, {e(C.ROLE)} at {e(C.AFFILIATION)}. Research on cross-chain interoperability, zero-knowledge proofs, smart contract security and decentralized identity.">
  <meta name="color-scheme" content="light">
  <meta name="theme-color" content="#f6f3ec">
  <meta property="og:title" content="{e(C.FULL_NAME)} · {e(C.ROLE)}">
  <meta property="og:description" content="{e(C.MOTTO.capitalize())}. Publications on cross-chain security, ZK and decentralized identity.">
  <meta property="og:url" content="{e(C.SITE_URL)}">
  <meta property="og:image" content="{e(C.SITE_URL + C.PHOTO)}">
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect x='3' y='3' width='26' height='26' rx='6' fill='%23ffc730' stroke='%2316140f' stroke-width='3'/%3E%3Cpath d='M11 9h7a4 4 0 0 1 0 8h-7zM11 17h8a4 4 0 0 1 0 8h-8z' fill='none' stroke='%2316140f' stroke-width='3'/%3E%3C/svg%3E">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&family=Space+Grotesk:wght@400;500;700&family=Unbounded:wght@600;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="style.css">
  <script>document.documentElement.classList.add("js");setTimeout(function(){{if(!window.__ready)document.documentElement.classList.remove("js")}},2500)</script>
</head>
<body>
  <a class="skip" href="#main">Skip to content</a>

  <header class="nav">
    <a class="brand" href="#top"><span class="brand-mark">B</span><span>{e(C.NAME_TOP.title())} {e(C.NAME_BOTTOM.title())}</span></a>
    <nav aria-label="Sections">
      <a href="#about">About</a>
      <a href="#publications">Publications</a>
      <a href="#advisor">Advisor</a>
      <a href="#contact">Contact</a>
    </nav>
  </header>

  <main id="main">
    <section class="hero" id="top">
      <div class="hero-text">
        <p class="eyebrow"><span class="dot"></span>{e(C.ROLE)} · {e(C.AFFILIATION)}</p>
        <h1 class="hero-name" aria-label="{e(C.NAME_TOP)} {e(C.NAME_BOTTOM)}">
          <span class="line">{"".join(f'<span class="ch">{e(ch)}</span>' for ch in C.NAME_TOP)}</span>
          <span class="line line-2">{"".join(f'<span class="ch">{e(ch)}</span>' for ch in C.NAME_BOTTOM)}</span>
        </h1>
        <p class="hero-full">{e(C.FULL_NAME)} · {e(C.LOCATION)}</p>
        <p class="hero-tagline">Researching <span class="rotator" data-words='{e(json.dumps(C.TAGLINES))}'>{e(C.TAGLINES[0])}</span><span class="caret" aria-hidden="true"></span></p>
        <div class="hero-cta">
          <a class="btn btn-ink" href="#publications">Read my papers</a>
          <a class="btn" href="{e(C.SCHOLAR)}" target="_blank" rel="noopener">Google Scholar <span aria-hidden="true">↗</span></a>
        </div>
        <dl class="stats">
          <div><dt>Papers</dt><dd><span class="count" data-to="{len(pubs)}">{len(pubs)}</span></dd></div>
          <div><dt>Journals</dt><dd><span class="count" data-to="{counts['journal']}">{counts['journal']}</span></dd></div>
          <div><dt>Citations</dt><dd><span class="count" data-to="{C.CITATIONS}">{C.CITATIONS}</span>+</dd></div>
          <div><dt>Since</dt><dd>{first_year}</dd></div>
        </dl>
      </div>
      <div class="hero-3d" aria-hidden="true">
        <canvas id="chain"></canvas>
        <p class="hint">drag to rotate</p>
      </div>
    </section>

    <section class="quotes" aria-label="Quotes">
      <span class="quote-mark" aria-hidden="true">“</span>
      <div class="quote-stage">
        {quotes}
      </div>
      <div class="quote-dots" role="tablist" aria-label="Choose quote">
        {"".join(f'<button role="tab" aria-label="Quote {i + 1}"{" class=is-on" if i == 0 else ""} data-i="{i}"></button>' for i in range(len(C.QUOTES)))}
      </div>
    </section>

    <section class="section" id="about">
      <header class="section-head reveal">
        <span class="section-no">01</span>
        <h2>About</h2>
      </header>
      <div class="about-grid">
        <aside class="card about-card reveal">
          <img class="avatar" src="{e(C.PHOTO)}" alt="{e(C.FULL_NAME)}" width="400" height="400">
          <pre class="contract" aria-label="Profile summary"><code><span class="kw">contract</span> <span class="ty">Researcher</span> {{
{contract}}}</code></pre>
        </aside>
        <div class="about-copy reveal">
          {"".join(f"<p>{e(p)}</p>" for p in C.PROFILE)}
          <ul class="areas">
            {research}
          </ul>
        </div>
      </div>
    </section>

    <section class="section" id="publications">
      <header class="section-head reveal">
        <span class="section-no">02</span>
        <h2>Publications</h2>
        <div class="filters" role="group" aria-label="Filter publications">
          {"".join(filters)}
        </div>
      </header>
      <p class="legend reveal"><strong class="me">Bold</strong> is me · <span class="adv">underlined</span> is my advisor · full list on <a href="{e(C.SCHOLAR)}" target="_blank" rel="noopener">Google Scholar ↗</a></p>
      <ol class="pubs">
        {"".join(publication(i, p) for i, p in enumerate(pubs, 1))}
      </ol>
    </section>

    <section class="section" id="advisor">
      <header class="section-head reveal">
        <span class="section-no">03</span>
        <h2>Advisor &amp; Lab</h2>
      </header>
      <div class="advisor-grid">
        <div class="advisor-col reveal">
          <article class="card advisor">
            <img class="advisor-photo" src="{e(adv["photo"])}" alt="{e(adv["name"])}" width="239" height="239" loading="lazy">
            <div class="advisor-body">
              <p class="eyebrow">Research advisor</p>
              <h3>{e(adv["name"])} <span class="vi" lang="vi">{e(adv["name_vi"])}</span></h3>
              <p class="advisor-role">{e(adv["title"])}<br>{e(adv["org"])}</p>
              <p>{e(adv["blurb"])}</p>
              <ul class="chips">{"".join(f"<li>{e(x)}</li>" for x in adv["interests"])}</ul>
              <p class="joint"><b>{joint}/{len(pubs)}</b> of my papers are co-authored with him</p>
            </div>
          </article>
          <div class="advisor-contact">
            <a class="mail" href="mailto:{e(adv["email"])}"><span aria-hidden="true">✉</span> {e(adv["email"])}</a>
            {"".join(ext(l, u) for l, u in adv["links"])}
          </div>
        </div>
        <a class="card lab reveal" href="{e(lab["url"])}" target="_blank" rel="noopener">
          <span class="lab-mark" aria-hidden="true"><span></span><span></span><span></span></span>
          <p class="eyebrow">Research group</p>
          <h3>{e(lab["name"])}</h3>
          <p>{e(lab["tagline"])}</p>
          <p class="lab-org">{e(lab["org"])}</p>
          <span class="lab-url">{e(lab["url"].split("//")[1].rstrip("/"))} <span aria-hidden="true">↗</span></span>
        </a>
      </div>
    </section>

    <section class="section" id="contact">
      <div class="end-grid">
        <div class="reveal">
          <header class="section-head">
            <span class="section-no">04</span>
            <h2>Stack</h2>
          </header>
          <div class="stack">
            {stack}
          </div>
        </div>
        <div class="reveal">
          <header class="section-head">
            <span class="section-no">05</span>
            <h2>Contact</h2>
          </header>
          <p class="contact-lead">Open to collaboration on cross-chain security, zero-knowledge systems and decentralized identity.</p>
          <div class="contact-links">
            {links}
          </div>
        </div>
      </div>
    </section>
  </main>

  <footer class="footer">
    <p class="motto">{e(C.MOTTO)}</p>
    <p>© {max(p["year"] for p in pubs)} {e(C.FULL_NAME)} · Built from the same <code>content.py</code> as my <a href="https://github.com/{e(C.GITHUB_USER)}">GitHub profile</a>.</p>
  </footer>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.2/anime.min.js" defer></script>
  <script type="importmap">{{"imports": {{"three": "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js"}}}}</script>
  <script type="module" src="main.js"></script>
</body>
</html>
"""
    os.makedirs(SITE, exist_ok=True)
    with open(os.path.join(SITE, "index.html"), "w") as f:
        f.write(html)
    print("  site/index.html")


if __name__ == "__main__":
    build()
